language: scala

jdk: openjdk8

scala:
   - 2.12.4

services:
  - docker

script:
  #- sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION docker:publishLocal
  - pip install --user awscli
  - export PATH=$PATH:/$HOME/.local/bin
  - eval $(aws ecr get-login --region eu-west-1)
  - $(aws ecr get-login --no-include-email --region eu-west-1)
  - docker tag sample-akka-consul:latest $AWS_ACCOUNT_NUMBER.dkr.ecr.eu-west-1.amazonaws.com/sample-akka-consul:latest
  - docker push $AWS_ACCOUNT_NUMBER.dkr.ecr.eu-west-1.amazonaws.com/sample-akka-consul:latest
