version: '3.0'
services:
  sample-consul1:
    container_name: sample-consul1
    image: consul:latest
    command: consul agent -server -client=0.0.0.0 -bootstrap-expect=1 -data-dir=/tmp/consul -ui
    hostname: sample-consul1
    networks:
      - sample
    ports:
      - "8301:8300"
      - "8401:8400"
      - "8501:8500"
      - "8601:8600"
      - "9001:9001"

  sample-consul2:
    container_name: sample-consul2
    image: consul:latest
    command: consul agent -server -client=0.0.0.0 -rejoin -retry-join=sample-consul1 -data-dir=/tmp/consul -ui
    hostname: sample-consul2
    networks:
      - sample
    depends_on:
      - sample-consul1
    ports:
      - "8302:8300"
      - "8402:8400"
      - "8502:8500"
      - "8602:8600"
      - "9002:9001"


  sample-akka1:
    container_name: sample-akka1
    image: sample-akka-consul:latest
    hostname: sample-akka1
    networks:
      - sample
    depends_on:
      - sample-consul1
    ports:
      - "5001:5000"
      - "5011:5010"
      - "2550"
    environment:
      - CONSUL_HOST=sample-consul1
      - CONSUL_PORT=8500
      - CONSUL_AGENT=sample-consul1
      - SERVICE_AKKA_HOST=sample-akka1
      - SERVICE_AKKA_PORT=2550

  sample-akka2:
    container_name: sample-akka2
    image: sample-akka-consul:latest
    hostname: sample-akka2
    networks:
      - sample
    depends_on:
      - sample-consul1
    ports:
      - "5002:5000"
      - "5012:5010"
      - "2550"
    environment:
      - CONSUL_HOST=sample-consul1
      - CONSUL_PORT=8500
      - CONSUL_AGENT=sample-consul1
      - SERVICE_AKKA_HOST=sample-akka2
      - SERVICE_AKKA_PORT=2550

  sample-akka3:
    container_name: sample-akka3
    image: sample-akka-consul:latest
    hostname: sample-akka3
    networks:
      - sample
    depends_on:
      - sample-consul2
    ports:
      - "5003:5000"
      - "5013:5010"
      - "2550"
    environment:
      - CONSUL_HOST=sample-consul2
      - CONSUL_PORT=8500
      - CONSUL_AGENT=sample-consul2
      - SERVICE_AKKA_HOST=sample-akka3
      - SERVICE_AKKA_PORT=2550

  sample-akka4:
    container_name: sample-akka4
    image: sample-akka-consul:latest
    hostname: sample-akka4
    networks:
      - sample
    depends_on:
      - sample-consul2
    ports:
      - "5004:5000"
      - "5014:5010"
      - "2550"
    environment:
      - CONSUL_HOST=sample-consul2
      - CONSUL_PORT=8500
      - CONSUL_AGENT=sample-consul2
      - SERVICE_AKKA_HOST=sample-akka4
      - SERVICE_AKKA_PORT=2550

networks:
  sample:
    external:
      name: sample
